---

name: Deploy artifacts

on:
  workflow_run: ["gradle"]
  types:
    - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
        pattern: "*.zip"
      - name:
        run: unzip *.zip; rm -f *.zip
      - name: rsync deployment
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: >
            -axAXvS
            --delete
            --exclude="config.json"
            --rsync-path="sudo rsync"
          remote_host: host.terrashift.net
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
