name: Deploy artifacts

on:
  workflow_run:
    workflows: [Java CI with Gradle]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: MinecraftStats*
          extract: true
      - name: rsync deployment
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -axAXvS --delete --exclude="*config.json" --exclude="data/" --exclude="helper/"--rsync-path="sudo rsync"
          remote_host: host.terrashift.net
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
